export const XY_POSITION_CHANGE = 'XY_POSITION_CHANGE';
export const XY_POSITION_CHANGED = 'XY_POSITION_CHANGED';
export const TABLE_DIMENSIONS_CHANGED = 'TABLE_DIMENSIONS_CHANGED';
export const ROW_HEIGHT_CHANGED = 'ROW_HEIGHT_CHANGED';
export const COLUMN_RESIZE = 'COLUMN_RESIZE';